// <auto-generated />
using System;
using AuctionAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    [Migration("20250506093242_AddBidCount")]
    partial class AddBidCount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AuctionAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AuctionEndTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("BidCount")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsSold")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("StartingPrice")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuctionEndTime = new DateTime(2025, 5, 6, 9, 37, 41, 65, DateTimeKind.Utc).AddTicks(1029),
                            BidCount = 0,
                            CurrentPrice = 0m,
                            Description = "A beautifully ornate box said to contain all the evils of the world. Opening it released sorrow... and hope.",
                            ImageFileName = "pandoras box.jpg",
                            IsSold = false,
                            Name = "Pandora's Box",
                            StartingPrice = 500m
                        },
                        new
                        {
                            Id = 2,
                            AuctionEndTime = new DateTime(2025, 5, 6, 9, 39, 41, 65, DateTimeKind.Utc).AddTicks(1040),
                            BidCount = 0,
                            CurrentPrice = 0m,
                            Description = "Ancient dice used to divine fate. Roll carefully... each face reveals a destiny.",
                            ImageFileName = "Oracle's Dice.jpg",
                            IsSold = false,
                            Name = "Oracle's Dice",
                            StartingPrice = 300m
                        },
                        new
                        {
                            Id = 3,
                            AuctionEndTime = new DateTime(2025, 5, 6, 9, 36, 41, 65, DateTimeKind.Utc).AddTicks(1048),
                            BidCount = 0,
                            CurrentPrice = 0m,
                            Description = "Forged in the fires of the underworld and marked by Hades himself. A toll for the river Styx.",
                            ImageFileName = "Hades' Coin.jpg",
                            IsSold = false,
                            Name = "Hades' Coin",
                            StartingPrice = 250m
                        },
                        new
                        {
                            Id = 4,
                            AuctionEndTime = new DateTime(2025, 5, 6, 9, 37, 41, 65, DateTimeKind.Utc).AddTicks(1054),
                            BidCount = 0,
                            CurrentPrice = 0m,
                            Description = "A silver thread spun by unknown gods. Said to lead lost souls through forgotten paths.",
                            ImageFileName = "Thread of tyron.jpg",
                            IsSold = false,
                            Name = "The Thread of Tyron",
                            StartingPrice = 800m
                        },
                        new
                        {
                            Id = 5,
                            AuctionEndTime = new DateTime(2025, 5, 6, 9, 40, 41, 65, DateTimeKind.Utc).AddTicks(1057),
                            BidCount = 0,
                            CurrentPrice = 0m,
                            Description = "A cursed mirror that once reflected the gaze of Medusa. Some say it still can.",
                            ImageFileName = "Medusa's Mirror.jpg",
                            IsSold = false,
                            Name = "Medusa’s Mirror",
                            StartingPrice = 600m
                        },
                        new
                        {
                            Id = 6,
                            AuctionEndTime = new DateTime(2025, 5, 6, 9, 37, 41, 65, DateTimeKind.Utc).AddTicks(1063),
                            BidCount = 0,
                            CurrentPrice = 0m,
                            Description = "A replica, yes... but still crackling with static. Handle with reverence.",
                            ImageFileName = "Zeus lightningbolt.jpg",
                            IsSold = false,
                            Name = "Zeus' Lightning Bolt",
                            StartingPrice = 1000m
                        },
                        new
                        {
                            Id = 7,
                            AuctionEndTime = new DateTime(2025, 5, 6, 9, 35, 41, 65, DateTimeKind.Utc).AddTicks(1085),
                            BidCount = 0,
                            CurrentPrice = 0m,
                            Description = "Brushing with this comb is said to make even the stars blush. Love lingers in every tooth.",
                            ImageFileName = "Aphrodite's Comb.jpg",
                            IsSold = false,
                            Name = "Aphrodite’s Comb",
                            StartingPrice = 450m
                        },
                        new
                        {
                            Id = 8,
                            AuctionEndTime = new DateTime(2025, 5, 6, 9, 37, 41, 65, DateTimeKind.Utc).AddTicks(1088),
                            BidCount = 0,
                            CurrentPrice = 0m,
                            Description = "Worn by Hades himself. With it, one vanishes from mortal and divine sight alike.",
                            ImageFileName = "helm-of-darkness.jpg",
                            IsSold = false,
                            Name = "Helm of Darkness",
                            StartingPrice = 1200m
                        },
                        new
                        {
                            Id = 9,
                            AuctionEndTime = new DateTime(2025, 5, 6, 9, 38, 41, 65, DateTimeKind.Utc).AddTicks(1092),
                            BidCount = 0,
                            CurrentPrice = 0m,
                            Description = "The forbidden nectar of the gods. They say a sip adds a century to your life.",
                            ImageFileName = "Ambrosia.jpg",
                            IsSold = false,
                            Name = "Ambrosia",
                            StartingPrice = 1000m
                        },
                        new
                        {
                            Id = 10,
                            AuctionEndTime = new DateTime(2025, 5, 6, 9, 41, 41, 65, DateTimeKind.Utc).AddTicks(1097),
                            BidCount = 0,
                            CurrentPrice = 0m,
                            Description = "Winged and enchanted, made for swift travel between worlds and whispering winds.",
                            ImageFileName = "hermes-sandals.jpg",
                            IsSold = false,
                            Name = "Hermes’ Sandals",
                            StartingPrice = 700m
                        },
                        new
                        {
                            Id = 11,
                            AuctionEndTime = new DateTime(2025, 5, 6, 9, 40, 41, 65, DateTimeKind.Utc).AddTicks(1100),
                            BidCount = 0,
                            CurrentPrice = 0m,
                            Description = "A forged replica of Mjölnir. Still surprisingly heavy. Lifting it may reveal your worth.",
                            ImageFileName = "Thors Hammer.jpg",
                            IsSold = false,
                            Name = "Thor’s Hammer",
                            StartingPrice = 950m
                        },
                        new
                        {
                            Id = 12,
                            AuctionEndTime = new DateTime(2025, 5, 6, 9, 37, 41, 65, DateTimeKind.Utc).AddTicks(1106),
                            BidCount = 0,
                            CurrentPrice = 0m,
                            Description = "Woven from the golden ram, its glow is said to grant fortune, or madness.",
                            ImageFileName = "The Golden Fleece.jpg",
                            IsSold = false,
                            Name = "Golden Fleece",
                            StartingPrice = 1100m
                        },
                        new
                        {
                            Id = 13,
                            AuctionEndTime = new DateTime(2025, 5, 6, 9, 37, 41, 65, DateTimeKind.Utc).AddTicks(1109),
                            BidCount = 0,
                            CurrentPrice = 0m,
                            Description = "Plucked from the trench’s darkest depths. Some say it whispers tides in ancient tongues.",
                            ImageFileName = "Poseidon's shell.jpg",
                            IsSold = false,
                            Name = "Poseidon’s Shell",
                            StartingPrice = 500m
                        },
                        new
                        {
                            Id = 14,
                            AuctionEndTime = new DateTime(2025, 5, 6, 9, 38, 41, 65, DateTimeKind.Utc).AddTicks(1115),
                            BidCount = 0,
                            CurrentPrice = 0m,
                            Description = "It shakes the sea. A weapon of command, control, and crashing waves.",
                            ImageFileName = "poseidons-trident.jpg",
                            IsSold = false,
                            Name = "Poseidon's Trident",
                            StartingPrice = 1300m
                        },
                        new
                        {
                            Id = 15,
                            AuctionEndTime = new DateTime(2025, 5, 6, 9, 37, 41, 65, DateTimeKind.Utc).AddTicks(1118),
                            BidCount = 0,
                            CurrentPrice = 0m,
                            Description = "An ancient spinning spindle, said to be cursed. One touch and the world falls quiet.",
                            ImageFileName = "spinning spindle.jpg",
                            IsSold = false,
                            Name = "The Spindle of Destiny",
                            StartingPrice = 400m
                        },
                        new
                        {
                            Id = 16,
                            AuctionEndTime = new DateTime(2025, 5, 6, 9, 41, 41, 65, DateTimeKind.Utc).AddTicks(1123),
                            BidCount = 0,
                            CurrentPrice = 0m,
                            Description = "Perfect and red... a single bite seals your fate. Still fresh after centuries.",
                            ImageFileName = "Poison apple.jpg",
                            IsSold = false,
                            Name = "Poison Apple of Death",
                            StartingPrice = 380m
                        },
                        new
                        {
                            Id = 17,
                            AuctionEndTime = new DateTime(2025, 5, 6, 9, 36, 41, 65, DateTimeKind.Utc).AddTicks(1127),
                            BidCount = 0,
                            CurrentPrice = 0m,
                            Description = "Glass-crafted destiny. If it fits, your path changes forever.",
                            ImageFileName = "Cinderella's slipper.jpg",
                            IsSold = false,
                            Name = "Cinderella’s Slipper",
                            StartingPrice = 620m
                        },
                        new
                        {
                            Id = 18,
                            AuctionEndTime = new DateTime(2025, 5, 6, 9, 36, 41, 65, DateTimeKind.Utc).AddTicks(1169),
                            BidCount = 0,
                            CurrentPrice = 0m,
                            Description = "Forged in the fires of Mount Doom. Grants invisibility — and a growing obsession.",
                            ImageFileName = "the-one-ring.jpg",
                            IsSold = false,
                            Name = "The One Ring",
                            StartingPrice = 1500m
                        },
                        new
                        {
                            Id = 19,
                            AuctionEndTime = new DateTime(2025, 5, 6, 9, 39, 41, 65, DateTimeKind.Utc).AddTicks(1172),
                            BidCount = 0,
                            CurrentPrice = 0m,
                            Description = "Captured in a magical vessel or locked within a chest, this kiss breaks the darkest curses.",
                            ImageFileName = "true-loves-kiss.jpg",
                            IsSold = false,
                            Name = "True Love’s Kiss",
                            StartingPrice = 900m
                        },
                        new
                        {
                            Id = 20,
                            AuctionEndTime = new DateTime(2025, 5, 6, 9, 37, 41, 65, DateTimeKind.Utc).AddTicks(1177),
                            BidCount = 0,
                            CurrentPrice = 0m,
                            Description = "Inscribed with cosmic secrets in glowing green script. The alchemical key to 'as above, so below.'",
                            ImageFileName = "emerald-tablet.jpg",
                            IsSold = false,
                            Name = "The Emerald Tablet",
                            StartingPrice = 1250m
                        },
                        new
                        {
                            Id = 21,
                            AuctionEndTime = new DateTime(2025, 5, 6, 9, 38, 41, 65, DateTimeKind.Utc).AddTicks(1181),
                            BidCount = 0,
                            CurrentPrice = 0m,
                            Description = "Forged in shadow and insight, this elusive deck reveals more than mere futures—it reveals veiled truths. Only the brave may draw from it.",
                            ImageFileName = "Tarot of the Veiled Realms.jpg",
                            IsSold = false,
                            Name = "Tarot of the Veiled Realms",
                            StartingPrice = 900m
                        },
                        new
                        {
                            Id = 22,
                            AuctionEndTime = new DateTime(2025, 5, 6, 9, 40, 41, 65, DateTimeKind.Utc).AddTicks(1186),
                            BidCount = 0,
                            CurrentPrice = 0m,
                            Description = "This violet-hued spirit board pulses with ancient presence. It speaks not only to the dead, but to forgotten echoes of magic itself.",
                            ImageFileName = "Enchanted Ouija Board.jpg",
                            IsSold = false,
                            Name = "The Enchanted Ouija Board",
                            StartingPrice = 850m
                        },
                        new
                        {
                            Id = 23,
                            AuctionEndTime = new DateTime(2025, 5, 6, 9, 43, 41, 65, DateTimeKind.Utc).AddTicks(1189),
                            BidCount = 0,
                            CurrentPrice = 0m,
                            Description = "A cursed hourglass that counts a hidden hour no one sees. Time rewinds for those who dare flip it.",
                            ImageFileName = "The Thirteenth Hour Sandglass.jpg",
                            IsSold = false,
                            Name = "The Thirteenth Hour Sandglass",
                            StartingPrice = 950m
                        },
                        new
                        {
                            Id = 24,
                            AuctionEndTime = new DateTime(2025, 5, 6, 9, 40, 41, 65, DateTimeKind.Utc).AddTicks(1194),
                            BidCount = 0,
                            CurrentPrice = 0m,
                            Description = "Glows only in total darkness. Believed to guide lost spirits home.",
                            ImageFileName = "The Lantern of the Deep Moon.jpg",
                            IsSold = false,
                            Name = "The Lantern of the Deep Moon",
                            StartingPrice = 780m
                        },
                        new
                        {
                            Id = 25,
                            AuctionEndTime = new DateTime(2025, 5, 6, 9, 41, 41, 65, DateTimeKind.Utc).AddTicks(1196),
                            BidCount = 0,
                            CurrentPrice = 0m,
                            Description = "Carved from the last living tree in a cursed forest, this wand pulses with ancient magic. Its touch is strangely warm.",
                            ImageFileName = "The Wand of the Hollow Grove.jpg",
                            IsSold = false,
                            Name = "The Wand of the Hollow Grove",
                            StartingPrice = 750m
                        },
                        new
                        {
                            Id = 26,
                            AuctionEndTime = new DateTime(2025, 5, 6, 9, 37, 41, 65, DateTimeKind.Utc).AddTicks(1199),
                            BidCount = 0,
                            CurrentPrice = 0m,
                            Description = "A celestial map that charts constellations no longer in the sky. Some say they never were.",
                            ImageFileName = "The Atlas of Lost Stars.jpg",
                            IsSold = false,
                            Name = "The Atlas of Lost Stars",
                            StartingPrice = 940m
                        },
                        new
                        {
                            Id = 27,
                            AuctionEndTime = new DateTime(2025, 5, 6, 9, 38, 41, 65, DateTimeKind.Utc).AddTicks(1204),
                            BidCount = 0,
                            CurrentPrice = 0m,
                            Description = "Said to be woven by death herself. Whoever wears it sees beyond the veil of life.",
                            ImageFileName = "The Widow’s Veil.jpg",
                            IsSold = false,
                            Name = "The Widow’s Veil",
                            StartingPrice = 890m
                        },
                        new
                        {
                            Id = 28,
                            AuctionEndTime = new DateTime(2025, 5, 6, 9, 41, 41, 65, DateTimeKind.Utc).AddTicks(1207),
                            BidCount = 0,
                            CurrentPrice = 0m,
                            Description = "Flip it and hear the name of a place not on any map.",
                            ImageFileName = "The Coin of Forgotten Realms.jpg",
                            IsSold = false,
                            Name = "The Coin of Forgotten Realms",
                            StartingPrice = 880m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
